language: node_js
node_js:
  - "lts/*"
script:
  - yarn test:unit
  - yarn test:int
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn test:e2e:desktop; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn test:e2e:mobile; fi'
cache: yarn
